### ISSUE TITLE
Is site down?

### ISSUE THREAD

**Issue by frankli-dev** [porkchopclub/porkchop#123]
I couldn't access to https://porkchop.club/
It gives me 

```
This site can’t be reached
porkchop.club’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by jarednorman** [comment]
Thanks for your interest in Porkchop. The app was only ever set up for one ping pong table in an office in Victoria, BC, so unless you're in that office, access to it isn't of any use to you.

I believe the app is still running for that table (neither me nor the owner of the domain still work at that office) but I think they moved the app to an internal network or something.
